[book]
title = "USTC课程资源分享在线"
authors = ["Quaternijkon"]
language = "zh-CN"

[output.html]
additional-css = ["./additional/whichlang.css"]
additional-js = ["./additional/whichlang.js"]
git-repository-url = "https://github.com/Quaternijkon/ustc_course"
edit-url-template =  "https://github.com/Quaternijkon/ustc_course/edit/main/{path}"

[output.html.fold]
enable = true
level = 0

[preprocessor.katex]
after = ["links"]

[preprocessor.gitinfo]
enable = true
# choose placement(s)
header = false   # default: false
footer = true    # default: true
# common formatting
font-size   = "0.9em"
separator   = " • "
date-format = "%Y-%m-%d"
time-format = "%H:%M:%S"
branch      = "main"
hyperlink   = true  # make hash/branch clickable when possible
# optional timezone handling
timezone = "local"   # "local" (default) | "utc" | "source" | "fixed:+08:00"
[preprocessor.gitinfo.message]
footer = "Built {{date}}{{sep}}commit: {{hash}}"
