[book]
title = "USTC课程资源分享在线"
authors = ["Quaternijkon"]
language = "zh-CN"

[output.html]
git-repository-url = "https://github.com/Quaternijkon/ustc_course"
edit-url-template =  "https://github.com/Quaternijkon/ustc_course/edit/main/{path}"

[output.html.fold]
enable = true
level = 0

[preprocessor.katex]
after = ["links"]